language: java
jdk: oraclejdk11
install: 
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -f ./UserService/pom.xml
script:
  - mvn test -f UserService/pom.xml
  - mvn test -f AuthService/pom.xml
  - mvn test -f CardServicee/pom.xml
  - mvn test -f RoomService/pom.xml
