version: "3.3"
services:
  asi-front:
    build: ASI-front
    networks:
      - asi-network
  asi-user-service:
    build: UserService
    networks:
      - asi-network
    ports:
      - "8081:8080"
  asi-auth-service:
    build: AuthService
    networks:
      - asi-network
  reverse-proxy:
    build: ReverseProxy
    ports:
      - "80:80"
    depends_on:
      - asi-front
      - asi-user-service
    networks:
      - asi-network

networks:
  asi-network:
    external: false
